#
# Travis CI build file for Hemajoo Incubation Software (HIS).
#

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

# Ubuntu - Fast-boot environment.
dist: trusty

language: java

jdk: 
  - oraclejdk8

services:
  - docker
  - postgresql

addons:
  postgresql: "9.6"

# Set some folders to be cached to increase the build speed. 
cache:
  - $HOME/.m2
  - target/

# Specify a display with xvfb for UI testing
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
	
#after_script: "cp hemajoo-incubation-parent/etc/deploy-settings.xml $HOME/.m2/settings.xml && mvn deploy -f hemajoo-incubation-parent/pom.xml"

# Build script is a Maven command.
script: mvn clean package -f hemajoo-incubation-parent/pom.xml

deploy:
  provider: script
  script: "cp hemajoo-incubation-parent/etc/deploy-settings.xml $HOME/.m2/settings.xml && mvn deploy -f hemajoo-incubation-parent/pom.xml"
  skip_cleanup: false
  on:
    # Set 'tags' to:
    # . 'true'  will force the deployment of the artifact after a successful build only when the commit is tagged. So even if a merge request to 'master' is successful, the built artifact will not be deployed to the repository.
    # . 'false' will force the deployment of the artifact after a successful build only when merged on the 'master' branch.
    tags: false
  only:
    - master

notifications:
  email:
    recipients:
    - christophe.resse@gmail.com
    on_success: change
    on_failure: always
  slack:
    rooms:
      # 'hemajoo' is the Slack workplace and 'travis-incubation' is the Slack channel.
      - hemajoo:lOkFRXlNg0sP7EhvnGUq3gZJ#travis-incubation